

- name: "Copy goss files to host"
  template:
    src: "{{ test_name }}.j2"
    dest: "{{ tmp_dir }}/{{ test_name }}_{{ test_case_name | default('default') }}.yml"
    mode: 0644

    
- name: "Run goss test"
  goss:
    path: "{{ tmp_dir }}/{{ test_name }}_{{ test_case_name | default('default') }}.yml"
    format: junit
    output_file: "{{ goss_results_dir }}/{{ test_name }}_{{ test_case_name | default('default') }}.xml"
  ignore_errors: yes
  register: goss_output

- name: "Retrieve test results"
  fetch:
    src: "{{ goss_results_dir }}/{{ test_name }}_{{ test_case_name | default('default') }}.xml"
    dest: "tests/{{ test_name }}_{{ test_case_name | default('default') }}.xml"
    flat: yes



- name: "Clean up tmp files in tmp_dir"
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "{{ tmp_dir }}/*.yml"

- name: "Clean up tmp files in goss_results_dir"
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "{{ goss_results_dir }}/*.xml"








#- name: "Manually fail on error"
#  fail:
#    msg: "Goss tests failed"
#  when: goss_output.failed is defined

#- name: "Debug goss_output"
#  debug:
#    msg: "{{ goss_output.stdout_lines }}"
